package main

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"math/big"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const (
	nodeIdentityFileName      = "node_identity.json"
	validatorIdentityFileName = "validator_identity.json"
	nodeWalletFileName        = "wallet.json"
	nodeIdentityVersion       = 1
	nodeIDPrefix              = "msc_"
	validatorIDPrefix         = "val_"
	nodeIDRandomLength        = 30
)

var nodeIDAlphabet = []byte("ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789")

type nodeIdentityFile struct {
	NodeID    string `json:"node_id"`
	CreatedAt string `json:"created_at"`
	Version   int    `json:"version"`
}

type validatorIdentityFile struct {
	NodeID               string `json:"node_id"`
	ValidatorID          string `json:"validator_id"`
	ValidatorPublicKey   string `json:"validator_public_key"`
	ValidatorFingerprint string `json:"validator_fingerprint"`
	DerivedFrom          string `json:"derived_from"`
	CreatedAt            string `json:"created_at"`
	Version              int    `json:"version"`
}

type nodeWalletFile struct {
	Address    string `json:"address"`
	PublicKey  string `json:"public_key"`
	PrivateKey string `json:"private_key"`
	KeyType    string `json:"key_type"`
	CreatedAt  string `json:"created_at"`
	Version    int    `json:"version"`
}

type startupNodeIdentity struct {
	NodeID       string
	DataDir      string
	NodePath     string
	IdentityPath string
	Created      bool
}

func isAutoGeneratedNodeID(nodeID string) bool {
	return strings.HasPrefix(strings.ToLower(strings.TrimSpace(nodeID)), nodeIDPrefix)
}

func normalizeNodeIdentityID(nodeID string) string {
	nodeID = strings.TrimSpace(nodeID)
	if isAutoGeneratedNodeID(nodeID) {
		return nodeID
	}
	return normalizeValidatorID(nodeID)
}

func nodeIdentityMapKey(nodeID string) string {
	nodeID = strings.TrimSpace(nodeID)
	if nodeID == "" {
		return ""
	}
	if isAutoGeneratedNodeID(nodeID) {
		return strings.ToLower(nodeID)
	}
	return normalizeValidatorID(nodeID)
}

func nodeIdentityMatchesRequested(storedID string, requestedID string) bool {
	storedID = strings.TrimSpace(storedID)
	requestedID = strings.TrimSpace(requestedID)
	if requestedID == "" {
		return true
	}
	if strings.EqualFold(storedID, requestedID) {
		return true
	}
	// Production nodes may already have a stable random network node identity
	// (`msc_...`) while the service command still passes the consensus
	// validator id (`VAL_...`) as --id. Keep the network identity stable and
	// let the validator key/fingerprint files guard consensus authority.
	return isAutoGeneratedNodeID(storedID) && !isAutoGeneratedNodeID(requestedID)
}

func duplicateNodeIdentityErrorMessage(nodeID string) string {
	nodeID = strings.TrimSpace(nodeID)
	if nodeID == "" {
		nodeID = "unknown"
	}
	return fmt.Sprintf("ERROR:\nDuplicate Node Identity Detected\n\nNode ID:\n%s\n\nDelete node_identity.json or use a different data directory.", nodeID)
}

func validatorIDFromPublicKey(pub []byte) string {
	if len(pub) != ed25519.PublicKeySize {
		return ""
	}
	sum := sha256.Sum256(pub)
	return validatorIDPrefix + hex.EncodeToString(sum[:16])
}

func loadOrCreateNodeWallet(nodePath string) (Wallet, string, error) {
	path := filepath.Join(nodePath, nodeWalletFileName)
	if stored, found, err := loadNodeWalletFile(path); err != nil {
		return Wallet{}, "", err
	} else if found {
		pub, err := hex.DecodeString(strings.TrimSpace(stored.PublicKey))
		if err != nil || len(pub) != ed25519.PublicKeySize {
			return Wallet{}, "", fmt.Errorf("node wallet %s has invalid public_key", path)
		}
		addr := strings.TrimSpace(stored.Address)
		if addr == "" {
			addr = AddressFromPublicKey(ed25519.PublicKey(pub))
		}
		return Wallet{PublicKey: ed25519.PublicKey(pub), Address: addr}, path, nil
	}

	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return Wallet{}, "", fmt.Errorf("generate node wallet key: %w", err)
	}
	wallet := Wallet{PublicKey: pub, Address: AddressFromPublicKey(pub)}
	stored := nodeWalletFile{
		Address:    wallet.Address,
		PublicKey:  hex.EncodeToString(pub),
		PrivateKey: hex.EncodeToString(priv),
		KeyType:    "ed25519",
		CreatedAt:  time.Now().UTC().Format(time.RFC3339),
		Version:    nodeIdentityVersion,
	}
	raw, err := json.MarshalIndent(stored, "", "  ")
	if err != nil {
		return Wallet{}, "", err
	}
	raw = append(raw, '\n')
	if err := writePrivateFile(path, raw); err != nil {
		return Wallet{}, "", err
	}
	return wallet, path, nil
}

func loadNodeWalletFile(path string) (nodeWalletFile, bool, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nodeWalletFile{}, false, nil
		}
		return nodeWalletFile{}, false, err
	}
	var stored nodeWalletFile
	if err := json.Unmarshal(raw, &stored); err != nil {
		return nodeWalletFile{}, true, fmt.Errorf("parse node wallet %s: %w", path, err)
	}
	return stored, true, nil
}

func nodeNetworkIdentity(n *Node) string {
	if n == nil {
		return ""
	}
	if id := normalizeNodeIdentityID(n.NetworkID); id != "" {
		return id
	}
	return normalizeNodeIdentityID(n.ID)
}

func nodeValidatorIdentity(n *Node) string {
	if n == nil {
		return ""
	}
	if id := strings.TrimSpace(n.ValidatorID); id != "" {
		return id
	}
	return validatorIDFromPublicKey(n.ValidatorKey.PublicKey)
}

func (n *Node) localConsensusValidatorIDCandidates() []string {
	if n == nil {
		return nil
	}
	out := make([]string, 0, 4)
	seen := make(map[string]struct{}, 4)
	add := func(id string) {
		id = normalizeValidatorID(id)
		if id == "" {
			return
		}
		if _, ok := seen[id]; ok {
			return
		}
		seen[id] = struct{}{}
		out = append(out, id)
	}
	if !isAutoGeneratedNodeID(n.ID) {
		add(n.ID)
	}
	add(n.ValidatorID)
	if id := validatorIDFromPublicKey(n.ValidatorKey.PublicKey); id != "" {
		add(id)
	}
	if !isAutoGeneratedNodeID(n.ValidatorKey.ID) {
		add(n.ValidatorKey.ID)
	}
	return out
}

func (n *Node) localConsensusValidatorID() string {
	candidates := n.localConsensusValidatorIDCandidates()
	if len(candidates) == 0 {
		return ""
	}
	return candidates[0]
}

func (n *Node) localConsensusValidatorIDForSet(validators []string) string {
	candidates := n.localConsensusValidatorIDCandidates()
	if len(candidates) == 0 {
		return ""
	}
	if len(validators) > 0 {
		for _, candidate := range candidates {
			if containsNormalizedValidatorID(validators, candidate) {
				return candidate
			}
		}
	}
	return candidates[0]
}

func (n *Node) localConsensusValidatorIDForHeight(height uint64) string {
	if n == nil {
		return ""
	}
	if height == 0 {
		height = n.currentEpoch()
	}
	var validators []string
	if height > 0 {
		validators = n.frozenValidatorsForHeight(height)
		if len(validators) == 0 {
			validators = n.GetConsensusValidators(int(height))
		}
	}
	return n.localConsensusValidatorIDForSet(validators)
}

func nodeWalletIdentity(n *Node) (string, string) {
	if n == nil {
		return "", ""
	}
	addr := strings.TrimSpace(n.WalletAddress)
	if addr == "" {
		addr = strings.TrimSpace(n.Wallet.Address)
	}
	pub := strings.TrimSpace(n.WalletPublicKey)
	if pub == "" && len(n.Wallet.PublicKey) == ed25519.PublicKeySize {
		pub = hex.EncodeToString(n.Wallet.PublicKey)
	}
	return addr, pub
}

func ensureNodeRuntimeSkeleton(nodePath, nodeID string) error {
	nodePath = strings.TrimSpace(nodePath)
	if nodePath == "" {
		return errors.New("node path is required")
	}
	if err := ensurePrivateDirectory(nodePath); err != nil {
		return err
	}
	for _, name := range []string{"chain.db", "snapshots", "blocks", "logs"} {
		if err := ensurePrivateDirectory(filepath.Join(nodePath, name)); err != nil {
			return err
		}
	}
	configPath := filepath.Join(nodePath, "config.toml")
	if _, err := os.Stat(configPath); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}
	config := fmt.Sprintf("# Generated by MSC Chain auto identity startup.\n[node]\nnode_id = %q\n", normalizeNodeIdentityID(nodeID))
	return writePrivateFile(configPath, []byte(config))
}

func writeValidatorIdentityFile(nodePath, nodeID string, vKey ValidatorKey) (string, string, error) {
	validatorID := validatorIDFromPublicKey(vKey.PublicKey)
	pubHex := ""
	if len(vKey.PublicKey) == ed25519.PublicKeySize {
		pubHex = hex.EncodeToString(vKey.PublicKey)
	}
	fp := validatorKeyFingerprint(vKey.PublicKey)
	path := filepath.Join(nodePath, validatorIdentityFileName)
	if validatorID == "" {
		_ = os.Remove(path)
		return "", path, nil
	}
	createdAt := time.Now().UTC().Format(time.RFC3339)
	if existing, found, err := loadValidatorIdentityFile(path); err == nil && found && strings.TrimSpace(existing.CreatedAt) != "" {
		createdAt = existing.CreatedAt
	}
	identity := validatorIdentityFile{
		NodeID:               normalizeNodeIdentityID(nodeID),
		ValidatorID:          validatorID,
		ValidatorPublicKey:   pubHex,
		ValidatorFingerprint: fp,
		DerivedFrom:          "validator_public_key_sha256",
		CreatedAt:            createdAt,
		Version:              nodeIdentityVersion,
	}
	raw, err := json.MarshalIndent(identity, "", "  ")
	if err != nil {
		return "", path, err
	}
	raw = append(raw, '\n')
	if err := writePrivateFile(path, raw); err != nil {
		return "", path, err
	}
	return validatorID, path, nil
}

func loadValidatorIdentityFile(path string) (validatorIdentityFile, bool, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return validatorIdentityFile{}, false, nil
		}
		return validatorIdentityFile{}, false, err
	}
	var identity validatorIdentityFile
	if err := json.Unmarshal(raw, &identity); err != nil {
		return validatorIdentityFile{}, true, err
	}
	return identity, true, nil
}

func defaultAutoNodeRoot() string {
	if root := strings.TrimSpace(os.Getenv("MSC_NODE_AUTO_ROOT")); root != "" {
		return root
	}
	home, err := os.UserHomeDir()
	if err != nil || strings.TrimSpace(home) == "" {
		return filepath.Join(".", ".mscchain", "nodes")
	}
	return filepath.Join(home, ".mscchain", "nodes")
}

func generateRandomNodeID() (string, error) {
	var b strings.Builder
	b.WriteString(nodeIDPrefix)
	max := big.NewInt(int64(len(nodeIDAlphabet)))
	for i := 0; i < nodeIDRandomLength; i++ {
		n, err := rand.Int(rand.Reader, max)
		if err != nil {
			return "", fmt.Errorf("generate node id entropy: %w", err)
		}
		b.WriteByte(nodeIDAlphabet[n.Int64()])
	}
	return b.String(), nil
}

func loadNodeIdentity(path string) (nodeIdentityFile, bool, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nodeIdentityFile{}, false, nil
		}
		return nodeIdentityFile{}, false, err
	}
	var identity nodeIdentityFile
	if err := json.Unmarshal(raw, &identity); err != nil {
		return nodeIdentityFile{}, true, fmt.Errorf("parse node identity %s: %w", path, err)
	}
	identity.NodeID = strings.TrimSpace(identity.NodeID)
	if identity.NodeID == "" {
		return nodeIdentityFile{}, true, fmt.Errorf("node identity %s has empty node_id", path)
	}
	if identity.Version == 0 {
		identity.Version = nodeIdentityVersion
	}
	return identity, true, nil
}

func saveNodeIdentity(path string, nodeID string) error {
	nodeID = strings.TrimSpace(nodeID)
	if nodeID == "" {
		return errors.New("node id is required")
	}
	if err := ensurePrivateDirectory(filepath.Dir(path)); err != nil {
		return err
	}
	identity := nodeIdentityFile{
		NodeID:    nodeID,
		CreatedAt: time.Now().UTC().Format(time.RFC3339),
		Version:   nodeIdentityVersion,
	}
	raw, err := json.MarshalIndent(identity, "", "  ")
	if err != nil {
		return err
	}
	raw = append(raw, '\n')
	return writePrivateFile(path, raw)
}

func createNodeIdentity(path string, nodeID string) error {
	nodeID = strings.TrimSpace(nodeID)
	if nodeID == "" {
		return errors.New("node id is required")
	}
	if err := ensurePrivateDirectory(filepath.Dir(path)); err != nil {
		return err
	}
	identity := nodeIdentityFile{
		NodeID:    nodeID,
		CreatedAt: time.Now().UTC().Format(time.RFC3339),
		Version:   nodeIdentityVersion,
	}
	raw, err := json.MarshalIndent(identity, "", "  ")
	if err != nil {
		return err
	}
	raw = append(raw, '\n')
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		return err
	}
	if _, err := f.Write(raw); err != nil {
		_ = f.Close()
		return err
	}
	if err := f.Sync(); err != nil {
		_ = f.Close()
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	if dir, err := os.Open(filepath.Dir(path)); err == nil {
		_ = dir.Sync()
		_ = dir.Close()
	}
	return nil
}

func resolveIdentityAtPath(path string, requestedID string, allowGenerate bool) (nodeIdentityFile, bool, error) {
	identity, found, err := loadNodeIdentity(path)
	if err != nil {
		return nodeIdentityFile{}, false, err
	}
	requestedID = strings.TrimSpace(requestedID)
	if found {
		if !nodeIdentityMatchesRequested(identity.NodeID, requestedID) {
			return nodeIdentityFile{}, false, fmt.Errorf("node identity mismatch: %s contains %s, requested %s", path, identity.NodeID, requestedID)
		}
		return identity, false, nil
	}
	if requestedID == "" {
		if !allowGenerate {
			return nodeIdentityFile{}, false, errors.New("node id is required")
		}
		var genErr error
		requestedID, genErr = generateRandomNodeID()
		if genErr != nil {
			return nodeIdentityFile{}, false, genErr
		}
	}
	if err := createNodeIdentity(path, requestedID); err != nil {
		if os.IsExist(err) {
			identity, found, loadErr := loadNodeIdentity(path)
			if loadErr != nil {
				return nodeIdentityFile{}, false, loadErr
			}
			if found {
				if !allowGenerate && !nodeIdentityMatchesRequested(identity.NodeID, requestedID) {
					return nodeIdentityFile{}, false, fmt.Errorf("node identity mismatch: %s contains %s, requested %s", path, identity.NodeID, requestedID)
				}
				return identity, false, nil
			}
		}
		return nodeIdentityFile{}, false, err
	}
	identity, _, err = loadNodeIdentity(path)
	if err != nil {
		return nodeIdentityFile{}, false, err
	}
	return identity, true, nil
}

func resolveStartupNodeIdentity(cliID, dataDir string, idExplicit, dataDirExplicit bool) (startupNodeIdentity, error) {
	_ = idExplicit
	cliID = strings.TrimSpace(cliID)
	dataDir = strings.TrimSpace(dataDir)
	if dataDir == "" {
		dataDir = "data"
	}

	if dataDirExplicit {
		requestedID := normalizeNodeIdentityID(cliID)
		nodePath := dataDir
		if legacyPath, ok := existingLegacyNodeDataPath(dataDir, requestedID); ok {
			nodePath = legacyPath
		}
		identityPath := filepath.Join(nodePath, nodeIdentityFileName)
		identity, created, err := resolveIdentityAtPath(identityPath, requestedID, requestedID == "")
		if err != nil {
			return startupNodeIdentity{}, err
		}
		runtimeID := identity.NodeID
		if requestedID != "" {
			runtimeID = requestedID
		}
		if err := ensureNodeRuntimeSkeleton(nodePath, runtimeID); err != nil {
			return startupNodeIdentity{}, err
		}
		return startupNodeIdentity{
			NodeID:       runtimeID,
			DataDir:      dataDir,
			NodePath:     nodePath,
			IdentityPath: identityPath,
			Created:      created,
		}, nil
	}

	if cliID != "" {
		nodePath := nodeDataPath(dataDir, cliID)
		identityPath := filepath.Join(nodePath, nodeIdentityFileName)
		identity, created, err := resolveIdentityAtPath(identityPath, cliID, false)
		if err != nil {
			return startupNodeIdentity{}, err
		}
		if err := ensureNodeRuntimeSkeleton(nodePath, identity.NodeID); err != nil {
			return startupNodeIdentity{}, err
		}
		return startupNodeIdentity{
			NodeID:       identity.NodeID,
			DataDir:      dataDir,
			NodePath:     nodePath,
			IdentityPath: identityPath,
			Created:      created,
		}, nil
	}

	root := defaultAutoNodeRoot()
	for i := 0; i < 8; i++ {
		nodeID, err := generateRandomNodeID()
		if err != nil {
			return startupNodeIdentity{}, err
		}
		nodePath := nodeDataPath(root, nodeID)
		identityPath := filepath.Join(nodePath, nodeIdentityFileName)
		if _, found, err := loadNodeIdentity(identityPath); err != nil {
			return startupNodeIdentity{}, err
		} else if found {
			continue
		}
		identity, created, err := resolveIdentityAtPath(identityPath, nodeID, false)
		if err != nil {
			return startupNodeIdentity{}, err
		}
		if err := ensureNodeRuntimeSkeleton(nodePath, identity.NodeID); err != nil {
			return startupNodeIdentity{}, err
		}
		return startupNodeIdentity{
			NodeID:       identity.NodeID,
			DataDir:      root,
			NodePath:     nodePath,
			IdentityPath: identityPath,
			Created:      created,
		}, nil
	}
	return startupNodeIdentity{}, errors.New("could not allocate unique random node identity")
}
