package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

const (
	// `persistentPeersFile` defines the constant value used by this package.
	persistentPeersFile = "peers.json"
	// `persistentValidatorsFile` defines the constant value used by this package.
	persistentValidatorsFile = "validators.json"
	// `validatorFreezeJournalFile` defines whether the related condition is satisfied.
	validatorFreezeJournalFile = "validator_freeze_journal.jsonl"
)

type ValidatorFreezeJournalEntry struct {
	// `Height` stores the value associated with this record.
	Height uint64 `json:"height"`
	// `ValidatorSetHash` stores whether the related condition is satisfied.
	ValidatorSetHash string `json:"validator_set_hash"`
	// `Validators` stores whether the related condition is satisfied.
	Validators []string `json:"validators"`
	// `RecordedAtUnix` stores the value associated with this record.
	RecordedAtUnix int64 `json:"recorded_at_unix,omitempty"`
}

type startupPeerReconcileEvent struct {
	// `Base` stores the value associated with this record.
	Base string
	// `OldPeerID` stores the value associated with this record.
	OldPeerID string
	// `NewPeerID` stores the value associated with this record.
	NewPeerID string
}

// existingLegacyNodeDataPath preserves the established node_<id> storage
// layout when an operator keeps passing its parent as --datadir. This check
// must run before accepting a newer root-level identity file: a failed or
// partial migration may have created root metadata while the authoritative
// chain databases still live in the legacy child directory.
func existingLegacyNodeDataPath(baseDir, nodeID string) (string, bool) {
	baseDir = strings.TrimSpace(baseDir)
	nodeID = strings.TrimSpace(nodeID)
	if baseDir == "" || nodeID == "" || isAutoGeneratedNodeID(nodeID) {
		return "", false
	}
	candidate := filepath.Join(filepath.Clean(baseDir), "node_"+nodeID)
	info, err := os.Stat(candidate)
	if err != nil || !info.IsDir() {
		return "", false
	}
	return candidate, true
}

// nodeDataPath implements the node data path helper.
func nodeDataPath(baseDir, nodeID string) string {
	baseDir = strings.TrimSpace(baseDir)
	nodeID = strings.TrimSpace(nodeID)
	cleanBase := filepath.Clean(baseDir)
	if legacyPath, ok := existingLegacyNodeDataPath(cleanBase, nodeID); ok {
		return legacyPath
	}
	if identity, found, err := loadNodeIdentity(filepath.Join(cleanBase, nodeIdentityFileName)); err == nil && found {
		if nodeIdentityMatchesRequested(identity.NodeID, nodeID) {
			return cleanBase
		}
	}
	if isAutoGeneratedNodeID(nodeID) &&
		strings.EqualFold(filepath.Base(cleanBase), "nodes") &&
		strings.EqualFold(filepath.Base(filepath.Dir(cleanBase)), ".mscchain") {
		return filepath.Join(baseDir, nodeID)
	}
	return filepath.Join(baseDir, "node_"+nodeID)
}

// mergePeerLists implements the merge peer lists helper.
func mergePeerLists(a, b []string) []string {
	// `uniq` stores the value produced by this operation.
	uniq := make(map[string]struct{}, len(a)+len(b))
	// `out` stores the result produced by this operation.
	out := make([]string, 0, len(a)+len(b))

	// `add` stores the value produced by this operation.
	add := func(p string) {
		if p == "" {
			return
		}
		// `ok` stores whether the related condition is satisfied.
		if _, ok := uniq[p]; ok {
			return
		}
		uniq[p] = struct{}{}
		out = append(out, p)
	}

	// `p` tracks the current values while iterating.
	for _, p := range a {
		add(p)
	}
	// `p` tracks the current values while iterating.
	for _, p := range b {
		add(p)
	}

	sort.Strings(out)
	return out
}

// splitPeerAddress implements the split peer address helper.
func splitPeerAddress(addr string) (base string, peerID string, hasPeerID bool) {
	addr = strings.TrimSpace(addr)
	if addr == "" {
		return "", "", false
	}

	// `idx` stores the current position in the related collection.
	idx := strings.Index(addr, "/p2p/")
	if idx < 0 {
		return addr, "", false
	}

	base = strings.TrimSpace(addr[:idx])
	peerID = strings.TrimSpace(addr[idx+len("/p2p/"):])
	// `slash` stores the value produced by this operation.
	if slash := strings.Index(peerID, "/"); slash >= 0 {
		peerID = strings.TrimSpace(peerID[:slash])
	}
	if base == "" || peerID == "" {
		return addr, "", false
	}
	return base, peerID, true
}

// sanitizePeerListWithPreferred keeps one peer ID per transport endpoint
// (e.g. /ip4/127.0.0.1/tcp/7001), preferring entries from preferred.
func sanitizePeerListWithPreferred(peers []string, preferred []string) []string {
	if len(peers) == 0 && len(preferred) == 0 {
		return nil
	}

	// `preferredByBase` stores the value produced by this operation.
	preferredByBase := make(map[string]string, len(preferred))
	// `preferredAddrByBase` stores the value produced by this operation.
	preferredAddrByBase := make(map[string]string, len(preferred))
	// `addr` tracks the address used by this operation.
	for _, addr := range preferred {
		// `base`, `pid`, and `hasPID` store the value produced by this operation.
		base, pid, hasPID := splitPeerAddress(addr)
		if !hasPID {
			continue
		}
		preferredByBase[base] = pid
		preferredAddrByBase[base] = fmt.Sprintf("%s/p2p/%s", base, pid)
	}

	// `out` stores the result produced by this operation.
	out := make([]string, 0, len(peers)+len(preferred))
	// `seen` stores the value produced by this operation.
	seen := make(map[string]struct{}, len(peers)+len(preferred))
	// `claimedBase` stores the value produced by this operation.
	claimedBase := make(map[string]string, len(peers)+len(preferred))

	// `add` stores the value produced by this operation.
	add := func(raw string) {
		// `addr` stores the address used by this operation.
		addr := strings.TrimSpace(raw)
		if addr == "" {
			return
		}
		// `base`, `pid`, and `hasPID` store the value produced by this operation.
		base, pid, hasPID := splitPeerAddress(addr)
		if hasPID {
			// `prefPID` and `ok` store whether the related condition is satisfied.
			if prefPID, ok := preferredByBase[base]; ok && prefPID != pid {
				return
			}
			// `existing` and `ok` store whether the related condition is satisfied.
			if existing, ok := claimedBase[base]; ok && existing != addr {
				return
			}
			claimedBase[base] = addr
		} else {
			// If this endpoint is pinned to a preferred /p2p/ identity, drop non-/p2p/ form.
			if _, ok := preferredByBase[base]; ok {
				return
			}
			// `existing` and `ok` store whether the related condition is satisfied.
			if existing, ok := claimedBase[base]; ok && existing != addr {
				return
			}
			claimedBase[base] = addr
		}

		// `ok` stores whether the related condition is satisfied.
		if _, ok := seen[addr]; ok {
			return
		}
		seen[addr] = struct{}{}
		out = append(out, addr)
	}

	// Pin preferred identities first so conflicting stale entries are rejected.
	for _, addr := range preferredAddrByBase {
		add(addr)
	}
	// `addr` tracks the address used by this operation.
	for _, addr := range peers {
		add(addr)
	}

	sort.Strings(out)
	return out
}

// reconcileLocalhostPeerIDsWithPersisted implements the reconcile localhost peer i ds with persisted helper.
func reconcileLocalhostPeerIDsWithPersisted(peers []string, persisted []string) ([]string, []startupPeerReconcileEvent) {
	if len(peers) == 0 || len(persisted) == 0 {
		return peers, nil
	}

	// `out` stores the result produced by this operation.
	out := append([]string(nil), peers...)
	// `configByBase` stores the configuration used by this operation.
	configByBase := make(map[string]string, len(peers))
	// `addr` tracks the address used by this operation.
	for _, addr := range peers {
		// `base` and `hasPeerID` store the value produced by this operation.
		base, _, hasPeerID := splitPeerAddress(addr)
		if !hasPeerID || !isLocalhostPeerAddr(addr) {
			continue
		}
		// `exists` stores whether the related condition is satisfied.
		if _, exists := configByBase[base]; exists {
			continue
		}
		configByBase[base] = strings.TrimSpace(addr)
	}

	// `events` stores the value produced by this operation.
	events := make([]startupPeerReconcileEvent, 0)
	// `addr` tracks the address used by this operation.
	for _, addr := range persisted {
		// `base`, `peerID`, and `hasPeerID` store the value produced by this operation.
		base, peerID, hasPeerID := splitPeerAddress(addr)
		if !hasPeerID || !isLocalhostPeerAddr(addr) {
			continue
		}
		// `configAddr` and `ok` store whether the related condition is satisfied.
		configAddr, ok := configByBase[base]
		if !ok {
			continue
		}
		// `configPeerID` and `configHasPeerID` store the configuration used by this operation.
		_, configPeerID, configHasPeerID := splitPeerAddress(configAddr)
		if !configHasPeerID || strings.EqualFold(strings.TrimSpace(configPeerID), strings.TrimSpace(peerID)) {
			continue
		}
		out = replacePeerAddrForBase(out, strings.TrimSpace(addr))
		configByBase[base] = strings.TrimSpace(addr)
		events = append(events, startupPeerReconcileEvent{
			Base:      base,
			OldPeerID: configPeerID,
			NewPeerID: peerID,
		})
	}

	return out, events
}

// loadPersistentPeers implements the load persistent peers helper.
func loadPersistentPeers(baseDir, nodeID string) []string {
	// `path` stores the value produced by this operation.
	path := filepath.Join(nodeDataPath(baseDir, nodeID), persistentPeersFile)
	// `data` and `err` store the error produced by this operation.
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	// `peers` stores the value used by this operation.
	var peers []string
	// `err` stores the error produced by this operation.
	if err := json.Unmarshal(data, &peers); err != nil {
		return nil
	}
	return peers
}

// savePersistentPeers implements the save persistent peers helper.
func savePersistentPeers(baseDir, nodeID string, peers []string) error {
	// `path` stores the value produced by this operation.
	path := filepath.Join(nodeDataPath(baseDir, nodeID), persistentPeersFile)
	// `data` and `err` store the error produced by this operation.
	data, err := json.MarshalIndent(peers, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0600)
}

// loadPersistentValidators implements the load persistent validators helper.
func loadPersistentValidators(baseDir, nodeID string) []string {
	// `path` stores the value produced by this operation.
	path := filepath.Join(nodeDataPath(baseDir, nodeID), persistentValidatorsFile)
	// `data` and `err` store the error produced by this operation.
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	// `validators` stores whether the related condition is satisfied.
	var validators []string
	// `err` stores the error produced by this operation.
	if err := json.Unmarshal(data, &validators); err != nil {
		return nil
	}
	return validators
}

// savePersistentValidators implements the save persistent validators helper.
func savePersistentValidators(baseDir, nodeID string, validators []string) error {
	// `path` stores the value produced by this operation.
	path := filepath.Join(nodeDataPath(baseDir, nodeID), persistentValidatorsFile)
	// `data` and `err` store the error produced by this operation.
	data, err := json.MarshalIndent(validators, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0600)
}

// loadValidatorFreezeJournal implements the load validator freeze journal helper.
func loadValidatorFreezeJournal(baseDir, nodeID string) []ValidatorFreezeJournalEntry {
	// `path` stores the value produced by this operation.
	path := filepath.Join(nodeDataPath(baseDir, nodeID), validatorFreezeJournalFile)
	// `file` and `err` store the error produced by this operation.
	file, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer file.Close()

	// `out` stores the result produced by this operation.
	out := make([]ValidatorFreezeJournalEntry, 0, 64)
	// `sc` stores the value produced by this operation.
	sc := bufio.NewScanner(file)
	// `buf` stores the value produced by this operation.
	buf := make([]byte, 0, 64*1024)
	sc.Buffer(buf, 4*1024*1024)
	for sc.Scan() {
		// `line` stores the value produced by this operation.
		line := strings.TrimSpace(sc.Text())
		if line == "" {
			continue
		}
		// `e` stores the value used by this operation.
		var e ValidatorFreezeJournalEntry
		// `err` stores the error produced by this operation.
		if err := json.Unmarshal([]byte(line), &e); err != nil {
			continue
		}
		out = append(out, e)
	}
	return out
}

// appendValidatorFreezeJournal implements the append validator freeze journal helper.
func appendValidatorFreezeJournal(baseDir, nodeID string, entry ValidatorFreezeJournalEntry) error {
	// `path` stores the value produced by this operation.
	path := filepath.Join(nodeDataPath(baseDir, nodeID), validatorFreezeJournalFile)
	// `err` stores the error produced by this operation.
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return err
	}
	// `f` and `err` store the error produced by this operation.
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0600)
	if err != nil {
		return err
	}
	defer f.Close()

	// `b` and `err` store the error produced by this operation.
	b, err := json.Marshal(entry)
	if err != nil {
		return err
	}
	// `err` stores the error produced by this operation.
	if _, err := f.Write(append(b, '\n')); err != nil {
		return err
	}
	return nil
}

// replayValidatorFreezeJournal implements the replay validator freeze journal helper.
func (n *Node) replayValidatorFreezeJournal() int {
	if n == nil {
		return 0
	}
	// `entries` stores the value produced by this operation.
	entries := loadValidatorFreezeJournal(n.DataDir, n.ID)
	if len(entries) == 0 {
		return 0
	}

	// `chainHeight` stores the value produced by this operation.
	chainHeight := uint64(0)
	if n.Blockchain != nil {
		chainHeight = n.Blockchain.Height()
	}
	// `maxHeight` stores the value produced by this operation.
	maxHeight := chainHeight + 1
	type validatedFreezeEntry struct {
		// `height` stores the value associated with this record.
		height uint64
		// `hash` stores the digest used to identify or verify the related data.
		hash string
		// `validators` stores whether the related condition is satisfied.
		validators []string
	}
	// `validated` stores whether the related condition is satisfied.
	validated := make([]validatedFreezeEntry, 0, len(entries))

	// `e` tracks the current values while iterating.
	for _, e := range entries {
		if e.Height == 0 || len(e.Validators) == 0 || e.Height > maxHeight {
			continue
		}
		// `vals` stores the value currently being processed.
		vals := canonicalValidatorIDs(e.Validators)
		if len(vals) == 0 {
			continue
		}
		// `hash` stores the digest used to identify or verify the related data.
		hash := strings.TrimSpace(e.ValidatorSetHash)
		if hash == "" {
			hash = ValidatorSetHash(vals)
		}
		if !n.validatorSetIDsMatchCommittedHash(e.Height, hash, vals) {
			continue
		}
		// Startup hardening: never replay a frozen set entry that disagrees with
		// an already-persisted chain block hash at the same height. This prevents
		// stale local journals from poisoning validator-set expectations after restarts.
		if n.Blockchain != nil {
			// `blk` and `ok` store whether the related condition is satisfied.
			if blk, ok := n.Blockchain.GetBlock(e.Height); ok {
				// `chainHash` stores the digest used to identify or verify the related data.
				chainHash := strings.TrimSpace(blk.ValidatorSetHash)
				if chainHash != "" && !strings.EqualFold(chainHash, hash) {
					continue
				}
			}
		}
		validated = append(validated, validatedFreezeEntry{
			height:     e.Height,
			hash:       hash,
			validators: vals,
		})
	}

	// `applied` stores the value produced by this operation.
	applied := 0
	n.validatorSetMu.Lock()
	if n.frozenValidatorsByHeight == nil {
		n.frozenValidatorsByHeight = make(map[uint64][]string)
	}
	if n.frozenValidatorHashByHeight == nil {
		n.frozenValidatorHashByHeight = make(map[uint64]string)
	}
	// `e` tracks the current values while iterating.
	for _, e := range validated {
		n.frozenValidatorsByHeight[e.height] = append([]string{}, e.validators...)
		n.frozenValidatorHashByHeight[e.height] = e.hash
		if e.height > n.freezeJournalLastHeight || (e.height == n.freezeJournalLastHeight && !strings.EqualFold(e.hash, n.freezeJournalLastHash)) {
			n.freezeJournalLastHeight = e.height
			n.freezeJournalLastHash = e.hash
		}
		applied++
	}
	n.validatorSetMu.Unlock()

	if DebugConsensus && applied > 0 {
		fmt.Printf("[SET-FREEZE-REPLAY] entries=%d applied=%d last_h=%d hash=%s\n",
			len(entries), applied, n.freezeJournalLastHeight, ShortHash(n.freezeJournalLastHash))
	}
	return applied
}

// syncFrozenValidatorSetHashesFromChain seeds frozen validator-set hashes from
// persisted chain blocks so restart logic stays chain-deterministic even if
// local freeze journal entries are stale.
func (n *Node) syncFrozenValidatorSetHashesFromChain() int {
	if n == nil || n.Blockchain == nil {
		return 0
	}

	// `tip` stores the value produced by this operation.
	tip := n.Blockchain.Height()
	if tip == 0 {
		return 0
	}

	// `applied` stores the value produced by this operation.
	applied := 0
	// `materialized` stores the value produced by this operation.
	materialized := 0
	// `missingHeights` stores the value produced by this operation.
	missingHeights := make([]uint64, 0, 16)
	// `droppedStaleHeights` stores the value produced by this operation.
	droppedStaleHeights := make(map[uint64]bool)
	// `recentMaterializationWindow` defines the constant value used by this package.
	const recentMaterializationWindow uint64 = 128
	// `carrySearchWindow` caps hash-only backfills. Without a local validator
	// list, scanning all prior/future heights turns sparse historical journals
	// into an O(n^2) startup loop on long-running nodes.
	const carrySearchWindow uint64 = 256
	// `shouldMaterializeMissingSet` stores the value produced by this operation.
	shouldMaterializeMissingSet := func(height uint64) bool {
		if height == 0 {
			return false
		}
		if tip <= recentMaterializationWindow {
			return true
		}
		if height == 1 || height == tip {
			return true
		}
		return height+recentMaterializationWindow >= tip
	}
	n.validatorSetMu.Lock()
	if n.frozenValidatorsByHeight == nil {
		n.frozenValidatorsByHeight = make(map[uint64][]string)
	}
	if n.frozenValidatorHashByHeight == nil {
		n.frozenValidatorHashByHeight = make(map[uint64]string)
	}
	// `findContiguousCarryValidators` stores the value produced by this operation.
	findContiguousCarryValidators := func(height uint64, wantHash string) []string {
		wantHash = strings.TrimSpace(wantHash)
		if height == 0 || wantHash == "" {
			return nil
		}
		// `prev` stores the value produced by this operation.
		searched := uint64(0)
		for prev := height; prev > 0 && searched < carrySearchWindow; prev-- {
			searched++
			// `prevHash` stores the digest used to identify or verify the related data.
			prevHash := strings.TrimSpace(n.frozenValidatorHashByHeight[prev])
			if prevHash == "" {
				continue
			}
			if !strings.EqualFold(prevHash, wantHash) {
				break
			}
			// `vals` stores the value currently being processed.
			if vals := canonicalValidatorIDs(n.frozenValidatorsByHeight[prev]); len(vals) > 0 {
				return vals
			}
		}
		return nil
	}
	// `findForwardContiguousCarryValidators` stores the value produced by this operation.
	findForwardContiguousCarryValidators := func(height uint64, wantHash string) []string {
		wantHash = strings.TrimSpace(wantHash)
		if height == 0 || wantHash == "" || height > tip {
			return nil
		}
		// `next` stores the value produced by this operation.
		searched := uint64(0)
		for next := height; next <= tip && searched < carrySearchWindow; next++ {
			searched++
			// `nextHash` stores the digest used to identify or verify the related data.
			nextHash := strings.TrimSpace(n.frozenValidatorHashByHeight[next])
			if nextHash == "" {
				continue
			}
			if !strings.EqualFold(nextHash, wantHash) {
				break
			}
			// `vals` stores the value currently being processed.
			if vals := canonicalValidatorIDs(n.frozenValidatorsByHeight[next]); len(vals) > 0 {
				return vals
			}
			if next == ^uint64(0) {
				break
			}
		}
		return nil
	}
	// `h` stores the value produced by this operation.
	for h := uint64(1); h <= tip; h++ {
		// `blk` and `ok` store whether the related condition is satisfied.
		blk, ok := n.Blockchain.GetBlock(h)
		if !ok {
			continue
		}
		// `chainHash` stores the digest used to identify or verify the related data.
		chainHash := strings.TrimSpace(blk.ValidatorSetHash)
		if chainHash == "" {
			continue
		}
		// `existingHash` stores the digest used to identify or verify the related data.
		existingHash := strings.TrimSpace(n.frozenValidatorHashByHeight[h])
		// If frozen validator IDs disagree with chain hash, drop the stale list.
		if vals := canonicalValidatorIDs(n.frozenValidatorsByHeight[h]); len(vals) > 0 {
			if !strings.EqualFold(existingHash, chainHash) && !strings.EqualFold(ValidatorSetHash(vals), chainHash) {
				if !n.stateHistoryPrunedForHeight(h) {
					delete(n.frozenValidatorsByHeight, h)
					droppedStaleHeights[h] = true
				}
			}
		}
		if !strings.EqualFold(existingHash, chainHash) {
			n.frozenValidatorHashByHeight[h] = chainHash
			if h > n.freezeJournalLastHeight || (h == n.freezeJournalLastHeight && !strings.EqualFold(chainHash, n.freezeJournalLastHash)) {
				n.freezeJournalLastHeight = h
				n.freezeJournalLastHash = chainHash
			}
			applied++
		}
		if len(n.frozenValidatorsByHeight[h]) == 0 && !droppedStaleHeights[h] {
			if !shouldMaterializeMissingSet(h) {
				continue
			}
			// `carry` stores the value produced by this operation.
			if carry := findContiguousCarryValidators(h-1, chainHash); len(carry) > 0 {
				n.frozenValidatorsByHeight[h] = append([]string{}, carry...)
			} else if carry := findForwardContiguousCarryValidators(h+1, chainHash); len(carry) > 0 {
				n.frozenValidatorsByHeight[h] = append([]string{}, carry...)
			} else if shouldMaterializeMissingSet(h) {
				missingHeights = append(missingHeights, h)
			}
		}
	}
	n.validatorSetMu.Unlock()

	// `h` tracks the current values while iterating.
	for _, h := range missingHeights {
		if len(n.frozenValidatorsForHeight(h)) > 0 {
			continue
		}
		// `validators`, `resolvedHash`, and `ok` store whether the related condition is satisfied.
		validators, resolvedHash, _, ok := n.resolveCommittedValidatorSetForHeight(h)
		if !ok || len(validators) == 0 {
			continue
		}
		validators = canonicalValidatorIDs(validators)
		if len(validators) == 0 {
			continue
		}
		// `expectedHash` stores the digest used to identify or verify the related data.
		expectedHash, _ := n.frozenValidatorSetHash(h)
		expectedHash = strings.TrimSpace(expectedHash)
		if expectedHash != "" {
			// `ok` stores whether the related condition is satisfied.
			if _, ok := n.validatorSetCandidateMatchesTarget(h, expectedHash, validators, nil); !ok {
				continue
			}
		}
		n.validatorSetMu.Lock()
		if len(n.frozenValidatorsByHeight[h]) == 0 {
			n.frozenValidatorsByHeight[h] = append([]string{}, validators...)
			if strings.TrimSpace(n.frozenValidatorHashByHeight[h]) == "" {
				resolvedHash = strings.TrimSpace(resolvedHash)
				if resolvedHash == "" {
					resolvedHash = strings.TrimSpace(n.preferredValidatorSetHashForHeight(h, validators, nil))
				}
				if resolvedHash == "" {
					resolvedHash = ValidatorSetHash(validators)
				}
				n.frozenValidatorHashByHeight[h] = resolvedHash
				if h > n.freezeJournalLastHeight || (h == n.freezeJournalLastHeight && !strings.EqualFold(resolvedHash, n.freezeJournalLastHash)) {
					n.freezeJournalLastHeight = h
					n.freezeJournalLastHash = resolvedHash
				}
			}
			materialized++
		}
		n.validatorSetMu.Unlock()
	}

	if DebugConsensus && (applied > 0 || materialized > 0) {
		fmt.Printf("[SET-FREEZE-CHAIN] applied=%d materialized=%d tip_h=%d hash=%s\n",
			applied, materialized, tip, ShortHash(n.freezeJournalLastHash))
	}
	return applied
}

// persistValidatorFreezeEntry implements the persist validator freeze entry helper.
func (n *Node) persistValidatorFreezeEntry(height uint64, validators []string, hash string) {
	if n == nil || height == 0 {
		return
	}
	// `vals` stores the value currently being processed.
	vals := canonicalValidatorIDs(validators)
	if len(vals) == 0 {
		return
	}
	hash = strings.TrimSpace(hash)
	if hash == "" {
		hash = ValidatorSetHash(vals)
	}

	n.validatorSetMu.Lock()
	if n.freezeJournalLastHeight == height && strings.EqualFold(n.freezeJournalLastHash, hash) {
		n.validatorSetMu.Unlock()
		return
	}
	n.freezeJournalLastHeight = height
	n.freezeJournalLastHash = hash
	n.validatorSetMu.Unlock()

	// `entry` stores the value produced by this operation.
	entry := ValidatorFreezeJournalEntry{
		Height:           height,
		ValidatorSetHash: hash,
		Validators:       append([]string{}, vals...),
		RecordedAtUnix:   time.Now().Unix(),
	}
	// `err` stores the error produced by this operation.
	if err := appendValidatorFreezeJournal(n.DataDir, n.ID, entry); err != nil && (DebugConsensus || DebugSync) {
		fmt.Printf("WARN freeze journal append failed: h=%d err=%v\n", height, err)
	}
}

// collectPeerMultiaddrs implements the collect peer multiaddrs helper.
func (n *Node) collectPeerMultiaddrs() []string {
	// `uniq` stores the value produced by this operation.
	uniq := make(map[string]struct{})

	// `p` tracks the current values while iterating.
	for _, p := range n.persistentPeersSnapshot() {
		if p == "" {
			continue
		}
		uniq[p] = struct{}{}
	}

	ValidatorAddrBook.mu.RLock()
	// `addr` tracks the address used by this operation.
	for _, addr := range ValidatorAddrBook.m {
		if addr == "" {
			continue
		}
		uniq[addr] = struct{}{}
	}
	ValidatorAddrBook.mu.RUnlock()

	if n.Host != nil {
		// `pid` tracks the current values while iterating.
		for _, pid := range n.Host.Network().Peers() {
			// `addrs` stores the address used by this operation.
			addrs := n.Host.Peerstore().Addrs(pid)
			// `addr` tracks the address used by this operation.
			for _, addr := range addrs {
				// `full` stores the value produced by this operation.
				full := fmt.Sprintf("%s/p2p/%s", addr.String(), pid.String())
				uniq[full] = struct{}{}
			}
		}
	}

	// `out` stores the result produced by this operation.
	out := make([]string, 0, len(uniq))
	// `p` tracks the current values while iterating.
	for p := range uniq {
		out = append(out, p)
	}
	return sanitizePeerListWithPreferred(out, n.trustedPeerMultiaddrs())
}

// persistLocalState implements the persist local state helper.
func (n *Node) persistLocalState() error {
	// `peers` stores the value produced by this operation.
	peers := n.collectPeerMultiaddrs()
	// `validators` stores whether the related condition is satisfied.
	validators := n.getValidatorList()

	// `err` stores the error produced by this operation.
	if err := savePersistentPeers(n.DataDir, n.ID, peers); err != nil {
		return err
	}
	// `err` stores the error produced by this operation.
	if err := savePersistentValidators(n.DataDir, n.ID, validators); err != nil {
		return err
	}
	return nil
}
